apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels
      app.kubernetes.io/name: argocd-server
  endpoints:
    - port: metrics
      interval: 30s