apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv2
spec:
  capacity: 
    storage: 10Gi
  nfs:
    server: 192.168.56.11
    path: /kubelog-kibana
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain