apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: server-hpa
spec: 
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    kind: Deployment
    name: server-test
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
